# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mtissari <mtissari@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/02 15:18:33 by mtissari          #+#    #+#              #
#    Updated: 2022/04/07 18:52:21 by mtissari         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

.PHONY := all re clean fclean make
ROOT := ./
FUNCTIONS := ft_2d_free.c ft_atoi.c ft_bzero.c ft_isalnum.c ft_isalpha.c \
ft_isascii.c ft_isdigit.c ft_isprint.c ft_itoa.c ft_lstadd_back.c ft_lstadd.c \
ft_lstcount.c ft_lstdel.c ft_lstdelone.c ft_lstfree.c ft_lstiter.c ft_lstmap.c \
ft_lstnew.c ft_memalloc.c ft_memccpy.c ft_memchr.c ft_memcmp.c ft_memcpy.c \
ft_memdel.c ft_memmove.c ft_memset.c ft_putchar_fd.c ft_putchar.c \
ft_putendl_fd.c ft_putendl.c ft_putnbr_fd.c ft_putnbr.c ft_putstr_fd.c \
ft_putstr.c ft_str_to_lst.c ft_strcat.c ft_strchr.c ft_strclr.c ft_strcmp.c \
ft_strcpy.c ft_strdel.c ft_strdup.c ft_strequ.c ft_striter.c ft_striteri.c \
ft_strjoin.c ft_strlcat.c ft_strlen.c ft_strmap.c ft_strmapi.c ft_strncat.c \
ft_strncmp.c ft_strncpy.c ft_strnequ.c ft_strnew.c ft_strnstr.c ft_strrchr.c \
ft_strsplit.c ft_strstr.c ft_strsub.c ft_strtrim.c ft_tolower.c ft_toupper.c
SOURCES := $(addprefix $(ROOT), $(FUNCTIONS))
INCLUDES := ./libft.h
O_FILES = $(SOURCES:.c=.o)
FLAGS := -Wall -Wextra -Werror -c
NAME := libft.a

$(NAME): $(SOURCES)
	@gcc $(FLAGS) -I $(INCLUDES) $(SOURCES)
	@ar rc $(NAME) $(O_FILES)
	ranlib $(NAME)

all: $(NAME)

clean:
	@rm -f $(O_FILES)

fclean: clean
	rm -f $(NAME)

re: fclean all
